name: Animation
description: Stories told through animated visuals, spanning a wide range of genres and styles.
conventions:
  - name: "Visual Storytelling"
    description: "The narrative is heavily conveyed through expressive animation and visual gags."
    importance: "essential"
  - name: "Family-Friendly Themes"
    description: "Often (but not always) targets a broad audience with accessible themes."
    importance: "typical"
  - name: "Personification"
    description: "Inanimate objects or animals are given human-like qualities."
    importance: "optional"
pacing_profile:
  name: "General"
  curve: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
character_archetypes:
  - name: "The Optimistic Protagonist"
    description: "A character with a positive outlook who overcomes challenges."
  - name: "The Comedic Sidekick"
    description: "A character who provides comic relief and supports the protagonist."
common_beats:
  - "INCITING_INCIDENT"
  - "MIDPOINT"
  - "RESOLUTION"
