name: Biographical
description: Stories based on the real life of a person or group of people.
conventions:
  - name: "Based on a True Story"
    description: "The narrative is grounded in historical events and real individuals."
    importance: "essential"
  - name: "Focus on a Key Period"
    description: "The story typically concentrates on a significant period in the subject's life."
    importance: "essential"
  - name: "Historical Context"
    description: "The narrative is interwoven with the historical and cultural context of the time."
    importance: "typical"
pacing_profile:
  name: "Drama"
  curve: [0.4, 0.5, 0.6, 0.5, 0.6, 0.7, 0.8]
character_archetypes:
  - name: "The Subject"
    description: "The central figure whose life is being depicted."
  - name: "The Confidant"
    description: "A close friend or family member who provides support and perspective."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "VICTORY"
  - "RESOLUTION"
