name: Comedy
description: Stories designed to be humorous and amusing.
conventions:
  - name: "Humorous Situations"
    description: "The plot is driven by a series of funny and often absurd situations."
    importance: "essential"
  - name: "Witty Dialogue"
    description: "The humor is often conveyed through clever and funny dialogue."
    importance: "essential"
  - name: "Happy Ending"
    description: "Comedies typically have a positive and uplifting resolution."
    importance: "typical"
pacing_profile:
  name: "Comedy"
  curve: [0.5, 0.6, 0.5, 0.7, 0.6, 0.8, 0.9]
character_archetypes:
  - name: "The Everyman"
    description: "A relatable protagonist who finds themselves in extraordinary situations."
  - name: "The Eccentric"
    description: "A quirky and unusual character who drives much of the humor."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "CLIMAX"
  - "RESOLUTION"
