name: Documentary
description: Non-fictional stories that present a particular subject in a factual and informative way.
conventions:
  - name: "Real-World Subject"
    description: "The narrative is focused on a real person, event, or issue."
    importance: "essential"
  - name: "Factual Information"
    description: "The story is presented with factual accuracy and often includes interviews and archival footage."
    importance: "essential"
  - name: "Point of View"
    description: "Documentaries often have a specific perspective or argument they are trying to make."
    importance: "typical"
pacing_profile:
  name: "General"
  curve: [0.4, 0.5, 0.6, 0.5, 0.6, 0.7, 0.8]
character_archetypes:
  - name: "The Expert"
    description: "An individual with deep knowledge of the subject matter."
  - name: "The Witness"
    description: "A person who has firsthand experience with the subject."
common_beats:
  - "INCITING_INCIDENT"
  - "REVELATION"
  - "RESOLUTION"
