name: Drama
description: Stories that focus on character development and emotional themes.
conventions:
  - name: "Character-Driven"
    description: "The plot is driven by the choices and relationships of the characters."
    importance: "essential"
  - name: "Emotional Conflict"
    description: "The story revolves around internal and interpersonal conflicts."
    importance: "essential"
  - name: "Serious Tone"
    description: "Dramas typically have a serious and thoughtful tone."
    importance: "typical"
pacing_profile:
  name: "Drama"
  curve: [0.4, 0.5, 0.6, 0.5, 0.6, 0.7, 0.8]
character_archetypes:
  - name: "The Protagonist"
    description: "The central character who undergoes significant emotional development."
  - name: "The Antagonist"
    description: "A character who creates conflict for the protagonist."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "CLIMAX"
  - "RESOLUTION"
