name: Fantasy
description: Stories set in imaginary worlds with magical or supernatural elements.
conventions:
  - name: "Magical Systems"
    description: "The world has a defined system of magic or supernatural powers."
    importance: "essential"
  - name: "World-Building"
    description: "The story takes place in a detailed and immersive fictional world."
    importance: "essential"
  - name: "Epic Quests"
    description: "The plot often revolves around a grand quest or journey."
    importance: "typical"
pacing_profile:
  name: "Action/Adventure"
  curve: [0.2, 0.5, 0.4, 0.8, 0.6, 0.9, 1.0]
character_archetypes:
  - name: "The Chosen One"
    description: "A protagonist destined to save the world or fulfill a prophecy."
  - name: "The Wise Mentor"
    description: "An older character who guides the protagonist."
common_beats:
  - "INCITING_INCIDENT"
  - "PLOT_POINT_1"
  - "MIDPOINT"
  - "PLOT_POINT_2"
  - "CLIMAX"
  - "RESOLUTION"
