name: Historical
description: Stories set in the past, often with a focus on historical events and figures.
conventions:
  - name: "Historical Setting"
    description: "The story takes place in a specific and recognizable historical period."
    importance: "essential"
  - name: "Period Detail"
    description: "The narrative includes accurate details about the customs, clothing, and technology of the era."
    importance: "essential"
  - name: "Fictional Characters in a Real World"
    description: "The story often features fictional characters interacting with historical events and figures."
    importance: "typical"
pacing_profile:
  name: "Drama"
  curve: [0.4, 0.5, 0.6, 0.5, 0.6, 0.7, 0.8]
character_archetypes:
  - name: "The Observer"
    description: "A character who provides a window into the historical events."
  - name: "The Historical Figure"
    description: "A real person from history who plays a role in the story."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "REVELATION"
  - "RESOLUTION"
