# Historical Genre Template
name: "historical"
description: "Stories set in past time periods with authentic historical detail"

conventions:
  pacing:
    - "Period-appropriate storytelling rhythm"
    - "Historical events drive plot progression"
    - "Character arcs reflect historical context"
  
  structure:
    act_one:
      - "Establish historical time and place"
      - "Introduce characters within historical context"
      - "Historical conflict or event begins"
    act_two:
      - "Characters navigate historical challenges"
      - "Historical forces create obstacles"
      - "Personal stories intersect with history"
      - "Historical climax approaches"
    act_three:
      - "Resolution within historical framework"
      - "Characters' fates tied to historical outcome"
      - "Historical perspective on events"

  character_archetypes:
    - "Historical figure or inspired character"
    - "Common person caught in history"
    - "Representative of historical opposing force"
    - "Observer or chronicler of events"

  common_elements:
    - "Authentic period details and customs"
    - "Historical events and figures"
    - "Social and political contexts"
    - "Period-appropriate language and behavior"
    - "Themes relevant to historical period"

authenticity_markers:
  required:
    - historical_accuracy: "Faithful representation of historical facts and context"
    - period_authenticity: "Convincing portrayal of historical time period"
    - thematic_relevance: "Story themes resonate with historical significance"
  
confidence_thresholds:
  minimum: 0.75
  excellent: 0.90