name: Horror
description: Stories designed to frighten, scare, or disgust.
conventions:
  - name: "Atmosphere of Dread"
    description: "The story creates a sense of fear and suspense."
    importance: "essential"
  - name: "Supernatural or Psychological Threat"
    description: "The conflict comes from a monstrous or psychological force."
    importance: "essential"
  - name: "Jump Scares"
    description: "The story uses sudden and shocking moments to startle the audience."
    importance: "optional"
pacing_profile:
  name: "Thriller"
  curve: [0.6, 0.4, 0.7, 0.5, 0.8, 0.6, 1.0]
character_archetypes:
  - name: "The Final Girl"
    description: "A resourceful female protagonist who survives to confront the killer."
  - name: "The Skeptic"
    description: "A character who refuses to believe in the supernatural threat until it's too late."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "CLIMAX"
  - "RESOLUTION"
