name: Mystery
description: Stories that revolve around a puzzle or a crime that needs to be solved.
conventions:
  - name: "Central Puzzle"
    description: "The plot is driven by the investigation of a central question or crime."
    importance: "essential"
  - name: "Clues and Red Herrings"
    description: "The story presents a series of clues and misleading information to the audience."
    importance: "essential"
  - name: "The Big Reveal"
    description: "The solution to the puzzle is revealed in a climactic scene."
    importance: "typical"
pacing_profile:
  name: "Mystery"
  curve: [0.3, 0.5, 0.4, 0.6, 0.5, 0.7, 1.0]
character_archetypes:
  - name: "The Detective"
    description: "The protagonist who investigates the mystery."
  - name: "The Femme Fatale"
    description: "A mysterious and seductive female character who may be a suspect or a client."
common_beats:
  - "INCITING_INCIDENT"
  - "REVELATION"
  - "TWIST"
  - "CLIMAX"
  - "RESOLUTION"
