name: Romance
description: Stories that focus on the development of a romantic relationship between two people.
conventions:
  - name: "Central Love Story"
    description: "The plot is driven by the development of a romantic relationship."
    importance: "essential"
  - name: "Obstacles to Love"
    description: "The couple faces a series of internal and external obstacles that they must overcome."
    importance: "essential"
  - name: "Happily Ever After"
    description: "The story typically ends with the couple together and happy."
    importance: "typical"
pacing_profile:
  name: "Romance"
  curve: [0.4, 0.6, 0.5, 0.7, 0.6, 0.8, 0.9]
character_archetypes:
  - name: "The Lovers"
    description: "The two protagonists who fall in love."
  - name: "The Rival"
    description: "A character who competes for the affection of one of the lovers."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "CLIMAX"
  - "RESOLUTION"
