# Science Fiction Genre Template
name: "sci-fi"
description: "Stories exploring futuristic concepts, technology, and scientific possibilities"

conventions:
  pacing:
    - "World-building exposition balanced with action"
    - "Technological reveals and discoveries"
    - "Escalating scientific/technological threats"
  
  structure:
    act_one:
      - "Establish futuristic world and rules"
      - "Introduce scientific concept or technology"
      - "Inciting incident involving sci-fi element"
    act_two:
      - "Explore implications of technology"
      - "Complications from scientific element"
      - "Characters adapt to new realities"
      - "Technology becomes threat or solution"
    act_three:
      - "Resolution using established sci-fi rules"
      - "Consequences of technological choices"
      - "New equilibrium or understanding"

  character_archetypes:
    - "Scientist or researcher"
    - "Space explorer or pilot"
    - "Artificial intelligence or android"
    - "Alien or enhanced human"

  common_elements:
    - "Advanced technology"
    - "Space travel or alien worlds"
    - "Time travel or parallel dimensions"
    - "Genetic engineering or enhancement"
    - "Artificial intelligence"

authenticity_markers:
  required:
    - world_building: "Consistent internal logic"
    - speculation: "Plausible scientific concepts"
    - exploration: "Examines implications of technology"
  
confidence_thresholds:
  minimum: 0.75
  excellent: 0.90