name: Sci-Fi
description: Stories that explore the impact of science and technology on society and individuals.
conventions:
  - name: "Advanced Technology"
    description: "The story features technology that is more advanced than what is currently available."
    importance: "essential"
  - name: "Exploration of Ideas"
    description: "The story often explores philosophical or social questions related to science and technology."
    importance: "essential"
  - name: "Future or Alien Setting"
    description: "The story is often set in the future or on another planet."
    importance: "typical"
pacing_profile:
  name: "Action/Adventure"
  curve: [0.2, 0.5, 0.4, 0.8, 0.6, 0.9, 1.0]
character_archetypes:
  - name: "The Scientist"
    description: "A character who is an expert in a particular field of science or technology."
  - name: "The Everyman"
    description: "A relatable protagonist who is caught up in the events of the story."
common_beats:
  - "INCITING_INCIDENT"
  - "REVELATION"
  - "CLIMAX"
  - "RESOLUTION"
