name: Thriller
description: Stories that are characterized by suspense, excitement, and a sense of impending doom.
conventions:
  - name: "High Stakes"
    description: "The conflict has significant, often life-or-death, consequences."
    importance: "essential"
  - name: "Fast-Paced Plot"
    description: "The story moves quickly, with a series of twists and turns."
    importance: "essential"
  - name: "Race Against Time"
    description: "The protagonist is often working against a deadline to prevent a catastrophe."
    importance: "typical"
pacing_profile:
  name: "Thriller"
  curve: [0.6, 0.4, 0.7, 0.5, 0.8, 0.6, 1.0]
character_archetypes:
  - name: "The Everyman Hero"
    description: "An ordinary person who is drawn into a dangerous situation."
  - name: "The Mastermind Villain"
    description: "An intelligent and ruthless antagonist who is always one step ahead."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "TWIST"
  - "CLIMAX"
  - "RESOLUTION"
