name: War
description: Stories that are set during a time of war, and often explore the experiences of soldiers and civilians.
conventions:
  - name: "War Setting"
    description: "The story takes place during a specific historical war."
    importance: "essential"
  - name: "Focus on the Human Cost"
    description: "The story explores the physical and psychological toll of war on individuals."
    importance: "essential"
  - name: "Combat Sequences"
    description: "The story often includes realistic and intense depictions of combat."
    importance: "typical"
pacing_profile:
  name: "Action/Adventure"
  curve: [0.2, 0.5, 0.4, 0.8, 0.6, 0.9, 1.0]
character_archetypes:
  - name: "The Young Recruit"
    description: "A naive and idealistic young soldier who is new to the horrors of war."
  - name: "The Grizzled Veteran"
    description: "An experienced and cynical soldier who has seen too much."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "VICTORY"
  - "RESOLUTION"
