name: Western
description: Stories that are set in the American West during the late 19th century.
conventions:
  - name: "Frontier Setting"
    description: "The story takes place in a sparsely populated and lawless region of the American West."
    importance: "essential"
  - name: "Cowboys and Outlaws"
    description: "The story features characters who are cowboys, gunslingers, and outlaws."
    importance: "essential"
  - name: "Showdowns and Duels"
    description: "The conflict is often resolved through a dramatic gunfight or duel."
    importance: "typical"
pacing_profile:
  name: "Action/Adventure"
  curve: [0.2, 0.5, 0.4, 0.8, 0.6, 0.9, 1.0]
character_archetypes:
  - name: "The Lone Gunslinger"
    description: "A mysterious and skilled gunman who is often a loner."
  - name: "The Town Sheriff"
    description: "A lawman who is responsible for maintaining order in a lawless town."
common_beats:
  - "INCITING_INCIDENT"
  - "SETBACK"
  - "CLIMAX"
  - "RESOLUTION"
